## ---- eventNames ----

eventNames <- list("Astronomical Low Tide" = c("ASTRONOMICAL LOW TIDE"),
                   "Avalanche" = c("AVALANCE",
                                   "AVALANCHE",
                                   "HEAVY SNOW/BLIZZARD/AVALANCHE"),
                   "Blizzard" = c("BLIZZARD",
                                  "BLIZZARD/WINTER STORM",
                                  "GROUND BLIZZARD",
                                  "HEAVY SNOW/BLIZZARD",
                                  "HIGH WIND/BLIZZARD"),
                   "Coastal Flood" = c("COASTAL  FLOODING/EROSION",
                                       "COASTAL EROSION",
                                       "COASTAL FLOOD",
                                       "COASTAL FLOODING",
                                       "COASTAL FLOODING/EROSION",
                                       "BEACH EROSION",
                                       "EROSION/CSTL FLOOD",
                                       "HEAVY SURF COASTAL FLOODING",
                                       "HIGH WINDS/COASTAL FLOOD"),
                   "Cold/Wind Chill" = c("COLD",
                                         "COLD AND WET CONDITIONS",
                                         "COLD TEMPERATURE",
                                         "COLD WAVE",
                                         "COLD WEATHER",
                                         "COLD/WIND CHILL",
                                         "COLD/WINDS",
                                         "EXTENDED COLD",
                                         "EXTREME COLD",
                                         "EXTREME COLD/WIND CHILL",
                                         "FOG AND COLD TEMPERATURES",
                                         "HIGH WINDS/COLD",
                                         "RECORD COLD",
                                         "SNOW/ BITTER COLD",
                                         "SNOW/COLD",
                                         "UNSEASONABLE COLD",
                                         "UNSEASONABLY COLD",
                                         "LOW TEMPERATURE",
                                         "COOL AND WET"),
                   "Debris Flow" = c(),
                   "Dense Fog" = c("DENSE FOG",
                                   "FOG"),
                   "Dense Smoke" = c("DENSE SMOKE"),
                   "Drought" = c("DROUGHT",
                                 "DROUGHT/EXCESSIVE HEAT",
                                 "HEAT WAVE DROUGHT"),
                   "Dust Devil" = c("DUST DEVIL"),
                   "Dust Storm" = c("DUST STORM",
                                    "DUST STORM/HIGH WINDS",
                                    "BLOWING DUST"),
                   "Excessive Heat" = c("EXTREME HEAT",
                                        "EXCESSIVE HEAT",
                                        "RECORD/EXCESSIVE HEAT"),
                   "Extreme Cold/Wind Chill" = c("EXTREME WIND CHILL",
                                                 "EXTREME WINDCHILL",
                                                 "HYPOTHERMIA",
                                                 "HYPOTHERMIA/EXPOSURE"),
                   "Flash Flood" = c(" FLASH FLOOD",
                                     "FLASH FLOOD",
                                     "FLASH FLOOD - HEAVY RAIN",
                                     "FLASH FLOOD FROM ICE JAMS",
                                     "FLASH FLOOD LANDSLIDES",
                                     "FLASH FLOOD WINDS",
                                     "FLASH FLOOD/",
                                     "FLASH FLOOD/ STREET",
                                     "FLASH FLOOD/FLOOD",
                                     "FLASH FLOOD/LANDSLIDE",
                                     "FLASH FLOODING",
                                     "FLASH FLOODING/FLOOD",
                                     "FLASH FLOODS",
                                     "FLOOD FLASH",
                                     "FLOOD/FLASH",
                                     "FLOOD/FLASH FLOOD",
                                     "FLOOD/FLASH/FLOOD",
                                     "FLOOD/FLASHFLOOD",
                                     "ICE STORM/FLASH FLOOD",
                                     "FLASH FLOODING/THUNDERSTORM WI"),
                   "Flood" = c("BREAKUP FLOODING",
                               "FLOOD",
                               "FLOOD & HEAVY RAIN",
                               "FLOOD/RAIN/WINDS",
                               "FLOOD/RIVER FLOOD",
                               "FLOODING",
                               "FLOODING/HEAVY RAIN",
                               "FLOODS",
                               "HEAVY RAIN AND FLOOD",
                               "HEAVY RAINS/FLOODING",
                               "HEAVY SNOW/HIGH WINDS & FLOOD",
                               "ICE JAM FLOOD (MINOR",
                               "ICE JAM FLOODING",
                               "MAJOR FLOOD",
                               "MINOR FLOODING",
                               "MUD SLIDES URBAN FLOODING",
                               "RIVER AND STREAM FLOOD",
                               "RIVER FLOOD",
                               "RIVER FLOODING",
                               "RURAL FLOOD",
                               "SMALL STREAM FLOOD",
                               "SNOWMELT FLOODING",
                               "TIDAL FLOODING",
                               "URBAN AND SMALL STREAM FLOODIN",
                               "URBAN FLOOD",
                               "URBAN FLOODING",
                               "URBAN FLOODS",
                               "URBAN/SMALL STREAM FLOOD",
                               "THUNDERSTORM WINDS/ FLOOD",
                               "THUNDERSTORM WINDS/FLOODING",
                               "HEAVY RAIN/SMALL STREAM URBAN",
                               "URBAN AND SMALL",
                               "URBAN SMALL",
                               "URBAN/SMALL STREAM",
                               "URBAN/SML STREAM FLD",
                               "DAM BREAK",
                               "DROWNING",
                               "HIGH WATER",
                               "RAPIDLY RISING WATER"),
                   "Frost/Freeze" = c("FREEZE",
                                      "FREEZING DRIZZLE",
                                      "FREEZING RAIN",
                                      "FREEZING RAIN/SLEET",
                                      "FREEZING RAIN/SNOW",
                                      "FREEZING SPRAY",
                                      "FROST/FREEZE",
                                      "FROST\\FREEZE",
                                      "HARD FREEZE",
                                      "HEAVY SNOW/FREEZING RAIN",
                                      "LIGHT FREEZING RAIN",
                                      "SNOW FREEZING RAIN",
                                      "SNOW/FREEZING RAIN",
                                      "SNOW/SLEET/FREEZING RAIN",
                                      "EARLY FROST",
                                      "FROST",
                                      "ICE",
                                      "ICE JAM",
                                      "ICE ON ROAD",
                                      "ICE ROADS",
                                      "ICY ROADS",
                                      "BLACK ICE",
                                      "GLAZE",
                                      "GLAZE ICE",
                                      "AGRICULTURAL FREEZE",
                                      "DAMAGING FREEZE"),
                   "Funnel Cloud" = c("FUNNEL CLOUD",
                                      "THUNDERSTORM WINDS/FUNNEL CLOU"),
                   "Freezing Fog" = c("FREEZING FOG"),
                   "Hail" = c("GUSTY WIND/HAIL",
                              "HAIL",
                              "HAIL 0.75",
                              "HAIL 075",
                              "HAIL 100",
                              "HAIL 125",
                              "HAIL 150",
                              "HAIL 175",
                              "HAIL 200",
                              "HAIL 275",
                              "HAIL 450",
                              "HAIL 75",
                              "HAIL DAMAGE",
                              "HAIL/WIND",
                              "HAIL/WINDS",
                              "HAILSTORM",
                              "SMALL HAIL",
                              "WIND/HAIL",
                              "THUNDERSTORM HAIL",
                              "THUNDERSTORM WIND/HAIL",
                              "THUNDERSTORM WINDS HAIL",
                              "THUNDERSTORM WINDS/HAIL",
                              "THUNDERSTORM WINDSHAIL",
                              "TORNADOES, TSTM WIND, HAIL",
                              "TSTM WIND/HAIL"),
                   "Heat" = c("UNSEASONABLY WARM",
                              "UNSEASONABLY WARM AND DRY",
                              "WARM WEATHER",
                              "HYPERTHERMIA/EXPOSURE",
                              "HEAT",
                              "HEAT WAVE",
                              "HEAT WAVES",
                              "RECORD HEAT"),
                   "Heavy Rain" = c("EXCESSIVE RAINFALL",
                                    "GUSTY WIND/HVY RAIN",
                                    "GUSTY WIND/RAIN",
                                    "HEAVY RAIN",
                                    "HEAVY RAIN/LIGHTNING",
                                    "HEAVY RAIN/SEVERE WEATHER",
                                    "HEAVY RAINS",
                                    "HIGH WINDS HEAVY RAINS",
                                    "HIGH WINDS/HEAVY RAIN",
                                    "HVY RAIN",
                                    "LIGHTNING AND HEAVY RAIN",
                                    "LIGHTNING/HEAVY RAIN",
                                    "RAIN",
                                    "RAIN/WIND",
                                    "RAINSTORM",
                                    "RECORD RAINFALL",
                                    "TORRENTIAL RAINFALL",
                                    "UNSEASONAL RAIN",
                                    "DOWNBURST",
                                    "HEAVY PRECIPITATION",
                                    "HEAVY SHOWER",
                                    "EXCESSIVE WETNESS"),
                   "Heavy Snow" = c("EXCESSIVE SNOW",
                                    "FALLING SNOW/ICE",
                                    "HEAVY LAKE SNOW",
                                    "HEAVY SNOW",
                                    "HEAVY SNOW AND HIGH WINDS",
                                    "HEAVY SNOW AND STRONG WINDS",
                                    "HEAVY SNOW SHOWER",
                                    "HEAVY SNOW SQUALLS",
                                    "HEAVY SNOW-SQUALLS",
                                    "HEAVY SNOW/ICE",
                                    "HEAVY SNOW/SQUALLS",
                                    "HEAVY SNOW/WIND",
                                    "HEAVY SNOW/WINTER STORM",
                                    "HEAVY SNOWPACK",
                                    "HIGH WIND/HEAVY SNOW",
                                    "HIGH WINDS/SNOW",
                                    "ICE AND SNOW",
                                    "LAKE EFFECT SNOW",
                                    "LAKE-EFFECT SNOW",
                                    "LATE SEASON SNOW",
                                    "LIGHT SNOW",
                                    "LIGHT SNOWFALL",
                                    "RECORD SNOW",
                                    "SNOW",
                                    "SNOW ACCUMULATION",
                                    "SNOW AND HEAVY SNOW",
                                    "SNOW AND ICE",
                                    "SNOW SQUALL",
                                    "SNOW SQUALLS",
                                    "SNOW/ ICE",
                                    "SNOW/HEAVY SNOW",
                                    "SNOW/HIGH WINDS",
                                    "SNOW/ICE",
                                    "SNOW/SLEET",
                                    "BLOWING SNOW",
                                    "SNOW/BLOWING SNOW",
                                    "COLD AND SNOW",
                                    "HEAVY RAIN/SNOW",
                                    "RAIN/SNOW"),
                   "High Surf" = c("   HIGH SURF ADVISORY",
                                   "HAZARDOUS SURF",
                                   "HEAVY RAIN/HIGH SURF",
                                   "HEAVY SURF",
                                   "HEAVY SURF AND WIND",
                                   "HEAVY SURF/HIGH SURF",
                                   "HIGH SURF",
                                   "ROUGH SURF",
                                   "HEAVY SEAS",
                                   "HEAVY SWELLS",
                                   "HIGH",
                                   "HIGH SEAS",
                                   "HIGH SWELLS",
                                   "HIGH WAVES",
                                   "ROGUE WAVE",
                                   "ROUGH SEAS"),
                   "High Wind" = c("GRADIENT WIND",
                                   "GUSTY WIND",
                                   "GUSTY WINDS",
                                   "HIGH  WINDS",
                                   "HIGH WIND",
                                   "HIGH WIND (G40)",
                                   "HIGH WIND 48",
                                   "HIGH WIND DAMAGE",
                                   "HIGH WINDS",
                                   "HIGH WINDS/",
                                   "ICE/STRONG WINDS",
                                   "NON-SEVERE WIND DAMAGE",
                                   "STORM FORCE WINDS",
                                   "STRONG WIND",
                                   "STRONG WINDS",
                                   "WIND DAMAGE",
                                   "WIND STORM",
                                   "WINDS",
                                   "SEVERE TURBULENCE",
                                   "GUSTNADO",
                                   "WIND"),
                   "Hurricane (Typhoon)" = c("HURRICANE",
                                             "HURRICANE EDOUARD",
                                             "HURRICANE EMILY",
                                             "HURRICANE ERIN",
                                             "HURRICANE FELIX",
                                             "HURRICANE GORDON",
                                             "HURRICANE OPAL",
                                             "HURRICANE-GENERATED SWELLS",
                                             "HURRICANE OPAL/HIGH WINDS",
                                             "TYPHOON",
                                             "HURRICANE/TYPHOON"),
                   "Ice Storm" = c("GLAZE/ICE STORM",
                                   "ICE STORM",
                                   "SLEET/ICE STORM",
                                   "SNOW AND ICE STORM",
                                   "SNOW/ICE STORM"),
                   "Lake-Effect Snow" = c(),
                   "Lakeshore Flood" = c("LAKE FLOOD",
                                         "LAKESHORE FLOOD"),
                   "Lightning" = c("LIGHTING",
                                   "LIGHTNING",
                                   "LIGHTNING  WAUSEON",
                                   "LIGHTNING INJURY",
                                   "LIGHTNING.",
                                   "TSTM WIND AND LIGHTNING",
                                   "LIGHTNING AND THUNDERSTORM WIN",
                                   "LIGHTNING THUNDERSTORM WINDS",
                                   "THUNDERSTORM WIND/LIGHTNING",
                                   "THUNDERSTORM WINDS LIGHTNING",
                                   "LIGNTNING"),
                   "Marine Hail" = c("MARINE HAIL"),
                   "Marine High Wind" = c("MARINE HIGH WIND",
                                          "HIGH WIND AND SEAS",
                                          "HIGH WIND/SEAS",
                                          "WIND AND WAVE"),
                   "Marine Strong Wind" = c("MARINE STRONG WIND"),
                   "Marine Thunderstorm Wind" = c("COASTAL STORM",
                                                  "COASTALSTORM"),
                   "Rip Current" = c("RIP CURRENT",
                                     "RIP CURRENTS",
                                     "RIP CURRENTS/HEAVY SURF"),
                   "Seiche" = c("SEICHE"),
                   "Sleet" = c("SLEET"),
                   "Storm Surge/Tide" = c("COASTAL SURGE",
                                          "STORM SURGE",
                                          "ASTRONOMICAL HIGH TIDE",
                                          "HIGH TIDES",
                                          "STORM SURGE/TIDE"),
                   "Strong Wind" = c(),
                   "Thunderstorm Wind" = c("MARINE THUNDERSTORM WIND",
                                           "SEVERE THUNDERSTORM",
                                           "SEVERE THUNDERSTORM WINDS",
                                           "SEVERE THUNDERSTORMS",
                                           "THUNDERESTORM WINDS",
                                           "THUNDERSNOW",
                                           "THUNDERSTORM",
                                           "THUNDERSTORM  WINDS",
                                           "THUNDERSTORM DAMAGE TO",
                                           "THUNDERSTORM WIND",
                                           "THUNDERSTORM WIND (G40)",
                                           "THUNDERSTORM WIND 60 MPH",
                                           "THUNDERSTORM WIND 65 MPH",
                                           "THUNDERSTORM WIND 65MPH",
                                           "THUNDERSTORM WIND 98 MPH",
                                           "THUNDERSTORM WIND G50",
                                           "THUNDERSTORM WIND G52",
                                           "THUNDERSTORM WIND G55",
                                           "THUNDERSTORM WIND G60",
                                           "THUNDERSTORM WIND TREES",
                                           "THUNDERSTORM WIND.",
                                           "THUNDERSTORM WIND/ TREE",
                                           "THUNDERSTORM WIND/ TREES",
                                           "THUNDERSTORM WIND/AWNING",
                                           "THUNDERSTORM WINDS",
                                           "THUNDERSTORM WINDS 13",
                                           "THUNDERSTORM WINDS 63 MPH",
                                           "THUNDERSTORM WINDS AND",
                                           "THUNDERSTORM WINDS G60",
                                           "THUNDERSTORM WINDS.",
                                           "THUNDERSTORM WINDS53",
                                           "THUNDERSTORM WINDSS",
                                           "THUNDERSTORM WINS",
                                           "THUNDERSTORMS",
                                           "THUNDERSTORMS WIND",
                                           "THUNDERSTORMS WINDS",
                                           "THUNDERSTORMW",
                                           "THUNDERSTORMWINDS",
                                           "THUNDERSTROM WIND",
                                           "THUNDERTORM WINDS",
                                           " TSTM WIND",
                                           " TSTM WIND (G45)",
                                           "MARINE TSTM WIND",
                                           "NON TSTM WIND",
                                           "NON-TSTM WIND",
                                           "TSTM WIND",
                                           "TSTM WIND  (G45)",
                                           "TSTM WIND (41)",
                                           "TSTM WIND (G35)",
                                           "TSTM WIND (G40)",
                                           "TSTM WIND (G45)",
                                           "TSTM WIND 40",
                                           "TSTM WIND 45",
                                           "TSTM WIND 55",
                                           "TSTM WIND 65)",
                                           "TSTM WIND DAMAGE",
                                           "TSTM WIND G45",
                                           "TSTM WIND G58",
                                           "TSTM WINDS",
                                           "TSTMW",
                                           "THUDERSTORM WINDS",
                                           "THUNDEERSTORM WINDS",
                                           "THUNERSTORM WINDS",
                                           "TUNDERSTORM WIND",
                                           "DRY MICROBURST",
                                           "MICROBURST",
                                           "WET MICROBURST",
                                           "MICROBURST WINDS",
                                           "DRY MIRCOBURST WINDS"),
                   "Tornado" = c("COLD AIR TORNADO",
                                 "TORNADO",
                                 "TORNADO F0",
                                 "TORNADO F1",
                                 "TORNADO F2",
                                 "TORNADO F3",
                                 "TORNADOES",
                                 "TORNDAO",
                                 "WHIRLWIND",
                                 "LANDSPOUT"),
                   "Tropical Depression" = c("TROPICAL DEPRESSION"),
                   "Tropical Storm" = c("TROPICAL STORM",
                                        "TROPICAL STORM ALBERTO",
                                        "TROPICAL STORM DEAN",
                                        "TROPICAL STORM GORDON",
                                        "TROPICAL STORM JERRY"),
                   "Tsunami" = c("TSUNAMI"),
                   "Volcanic Ash" = c("VOLCANIC ASH"),
                   "Waterspout" = c("WATERSPOUT",
                                    "WATERSPOUT-",
                                    "DUST DEVIL WATERSPOUT",
                                    "WATERSPOUT TORNADO",
                                    "WATERSPOUT-TORNADO",
                                    "WATERSPOUT/ TORNADO",
                                    "WATERSPOUT/TORNADO"),
                   "Wildfire" = c("LIGHTNING FIRE",
                                  "BRUSH FIRE",
                                  "FOREST FIRES",
                                  "GRASS FIRES",
                                  "WILD FIRES",
                                  "WILD/FOREST FIRE",
                                  "WILD/FOREST FIRES",
                                  "WILDFIRE",
                                  "WILDFIRES"),
                   "Winter Storm" = c("WINTER STORM",
                                      "WINTER STORMS",
                                      "WINTER STORM HIGH WINDS"),
                   "Winter Weather" = c("WINTER WEATHER",
                                        "WINTER WEATHER MIX",
                                        "WINTER WEATHER/MIX",
                                        "WINTRY MIX"),
                   "Other" = c("?",
                               "APACHE COUNTY",
                               "HEAVY MIX",
                               "MIXED PRECIP",
                               "MIXED PRECIPITATION",
                               "LANDSLIDE",
                               "LANDSLIDES",
                               "LANDSLUMP",
                               "MARINE ACCIDENT",
                               "MARINE MISHAP",
                               "MUD SLIDE",
                               "MUD SLIDES",
                               "MUDSLIDE",
                               "MUDSLIDES",
                               "OTHER",
                               "ROCK SLIDE",
                               "ICE FLOES"))
